(("default" . ((user-emacs-directory . "~/.emacs.d")))
 ("new-config" .  ((user-emacs-directory . "~/cloud/.personal/dotfiles/spacemacs_snapshot/")
									 env . (("SPACEMACSDIR" .  "~/cloud/.personal/dotfiles/spacemacs_snapshot/.emacs.d/"))))
 ("spip" . ((user-emacs-directory . "~/cloud/dotfiles/doomzzz/spipDoom/")))
 ("doodoo" . ((user-emacs-directory . "~/cloud/dotfiles/doomzzz/doodoo/"))))
